# Generated by Django 4.0.6 on 2022-07-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.CharField(max_length=64)),
                ('type_doing', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=64)),
            ],
        ),
    ]
