# Generated by Django 4.0.6 on 2022-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
