# Generated by Django 4.0.6 on 2022-07-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='direction',
        ),
        migrations.AddField(
            model_name='doc',
            name='directions',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.directions'),
        ),
    ]
