# Generated by Django 4.0.6 on 2022-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_city_country_doc_city_alter_doc_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=124),
        ),
    ]
