# Generated by Django 4.0.6 on 2022-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='Country',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
