# Generated by Django 4.0.6 on 2022-07-21 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_remove_doc_country_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('term', models.DateField(blank=True, null=True)),
                ('type_of_work', models.CharField(max_length=512)),
                ('cost', models.FloatField(max_length=64)),
                ('cost_nds', models.FloatField(max_length=64)),
                ('contacts', models.CharField(max_length=64)),
                ('number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.directions')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='treaties',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.treaties'),
        ),
    ]
