# Generated by Django 4.0.6 on 2022-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_treaties_doc_treaties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treaties',
            name='number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
