# Generated by Django 4.0.6 on 2022-07-21 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_alter_treaties_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=124)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='customers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.customers'),
        ),
    ]
