# Generated by Django 4.0.6 on 2022-07-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_typeso_doc_types_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='state_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.state'),
        ),
    ]
