# Generated by Django 4.0.6 on 2022-07-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_owner_alter_employee_owner'),
        ('doc', '0015_country_doc_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='Executor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='adr',
            field=models.CharField(max_length=164),
        ),
    ]
